[phases.setup]
nixPkgs = ['python310', 'nodejs-18_x']

[phases.install]
cmds = [
    'pip install jaclang',
    'npm install'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'jac serve app.jac --host 0.0.0.0 --port $PORT'
