[phases.setup]
nixPkgs = ['python310Full', 'nodejs-18_x']

[phases.install]
cmds = [
    'python3 -m venv .venv',
    '.venv/bin/pip install jaclang byllm',
    'npm install'
]

[phases.build]
cmds = ['npm run build']

[start]
cmd = '.venv/bin/jac serve app.jac --host 0.0.0.0 --port $PORT'
